"""Deterministically generate BSR2 fixed parameters without crypto libraries.

The generator uses only Python integer and byte operations. Its public seed,
state transition, warm-up count, output schedule, and selection rules are
specified in this file so anyone can reproduce the parameters.

This generator is a transparency/reproducibility tool. It is not an entropy
source and does not establish cryptographic security.
"""

from __future__ import annotations

import argparse
import json

MASK64 = (1 << 64) - 1
PARAMETER_SEED = b"BrisartSecurityResearch|BSR2|parameter-generation|v1"
STATE_WORDS = 8
WARMUP_STEPS = 192
ROUND_CONSTANT_COUNT = 24
ROTATION_COUNT = 8
PERMUTATION_SIZE = 16


def rotate_left(value: int, amount: int) -> int:
    amount %= 64
    value &= MASK64
    if amount == 0:
        return value
    return ((value << amount) | (value >> (64 - amount))) & MASK64


def initialize_state(seed: bytes = PARAMETER_SEED) -> list[int]:
    if not isinstance(seed, bytes) or not seed:
        raise ValueError("seed must be non-empty bytes")
    state = [0] * STATE_WORDS
    for index, value in enumerate(seed):
        lane = index % STATE_WORDS
        shift = ((index // STATE_WORDS) % 8) * 8
        state[lane] ^= (value + 1) << shift
        state[lane] &= MASK64
        state[lane] = (
            state[lane]
            + (index + 1) * (value + 1)
            + (lane + 1) * len(seed)
        ) & MASK64
        state[lane] = rotate_left(
            state[lane],
            ((value + index + lane) % 63) + 1,
        )
    return state


def transition(state: list[int], step: int, seed: bytes = PARAMETER_SEED) -> None:
    snapshot = state[:]
    seed_length = len(seed)
    for lane in range(STATE_WORDS):
        left = snapshot[(lane - 1) % STATE_WORDS]
        center = snapshot[lane]
        right = snapshot[(lane + 1) % STATE_WORDS]
        far = snapshot[(lane + 3) % STATE_WORDS]
        seed_byte = seed[(step + lane * 5) % seed_length]
        amount = ((seed_byte + step + lane * 11) % 63) + 1
        mixed = (
            center
            + (left ^ rotate_left(right, (lane + 1) * 3))
            + ((far & ~right) ^ ((step + 1) * (seed_byte + 1)))
            + ((lane + 1) << ((step + lane) % 17))
        ) & MASK64
        state[lane] = rotate_left(mixed ^ left ^ far, amount)


def word_stream(seed: bytes = PARAMETER_SEED):
    state = initialize_state(seed)
    for step in range(WARMUP_STEPS):
        transition(state, step, seed)
    step = WARMUP_STEPS
    while True:
        transition(state, step, seed)
        lane = step % STATE_WORDS
        value = (
            state[lane]
            ^ rotate_left(state[(lane + 2) % STATE_WORDS], 17)
            ^ rotate_left(state[(lane + 5) % STATE_WORDS], 41)
            ^ step
        ) & MASK64
        yield value
        step += 1


def take_unique_nonzero(stream, count: int) -> list[int]:
    values: list[int] = []
    seen: set[int] = set()
    while len(values) < count:
        value = next(stream) & MASK64
        if value == 0 or value in seen:
            continue
        seen.add(value)
        values.append(value)
    return values


def generate_rotations(stream) -> list[int]:
    rotations: list[int] = []
    used: set[int] = set()
    while len(rotations) < ROTATION_COUNT:
        candidate = (next(stream) % 63) + 1
        if candidate in used:
            continue
        used.add(candidate)
        rotations.append(candidate)
    return rotations


def generate_permutation(stream) -> list[int]:
    values = list(range(PERMUTATION_SIZE))
    for upper in range(PERMUTATION_SIZE - 1, 0, -1):
        index = next(stream) % (upper + 1)
        values[upper], values[index] = values[index], values[upper]
    if values == list(range(PERMUTATION_SIZE)):
        values[0], values[1] = values[1], values[0]
    return values


def generate_parameters(seed: bytes = PARAMETER_SEED) -> dict:
    stream = word_stream(seed)
    return {
        "generator_version": 1,
        "seed_ascii": seed.decode("ascii"),
        "warmup_steps": WARMUP_STEPS,
        "round_constants": take_unique_nonzero(stream, ROUND_CONSTANT_COUNT),
        "structural_constants": take_unique_nonzero(stream, 3),
        "rotations": generate_rotations(stream),
        "word_permutation": generate_permutation(stream),
    }


def python_block(parameters: dict) -> str:
    constant_lines = "\n".join(
        f"    0x{value:016X}," for value in parameters["round_constants"]
    )
    structural = parameters["structural_constants"]
    rotations = ", ".join(str(value) for value in parameters["rotations"])
    permutation = ", ".join(str(value) for value in parameters["word_permutation"])
    return (
        '# BSR2 parameters generated by tools/generate_bsr2_parameters.py\n'
        f'BSR2_PARAMETER_SEED = {parameters["seed_ascii"]!r}\n'
        'ROUND_CONSTANTS = (\n'
        f'{constant_lines}\n'
        ')\n'
        f'ROUND_INDEX_CONSTANT = 0x{structural[0]:016X}\n'
        f'LANE_INDEX_CONSTANT = 0x{structural[1]:016X}\n'
        f'INITIAL_STATE_CONSTANT = 0x{structural[2]:016X}\n'
        f'ROTATIONS = ({rotations})\n'
        f'WORD_PERMUTATION = ({permutation})\n'
    )


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate reproducible BSR2 parameters.")
    parser.add_argument("--json", action="store_true", help="Print JSON instead of Python.")
    args = parser.parse_args()
    parameters = generate_parameters()
    if args.json:
        print(json.dumps(parameters, indent=2))
    else:
        print(python_block(parameters), end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
